version: 0.1

env:
    variables:
        S3_BUCKET: "argmax-info-fe"
        APP_NAME: "argmax-info-fe"
        BUILD_ENV : "prod"
        BUILD_FOLDER: "dist"

phases:
    install:
        commands:
            - npm install -g @angular/cli
            - npm install

    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}

    post_build:
        commands:
            #- aws s3 rm s3://${S3_BUCKET}/${APP_NAME} --recursive
            #- echo S3 bucket is cleared.
            - aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive --acl public-read
        
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes


