version: 0.1

env:
    variables:
        S3_BUCKET: "argmax-info-fe"
        APP_NAME: "argmax-info-fe"
        BUILD_ENV : "prod"
        BUILD_FOLDER: "dist"

phases:
    install:
        commands:
            - npm install -g @angular/cli
            - npm install

    build:
        commands:
            - npm run build --prod

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes


